services:
  - type: web
    name: fixitlocal
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn raporprojesi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: raporprojesi.settings
      - key: PYTHON_VERSION
        value: 3.11.2