# Generated by Django 5.2 on 2025-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='diger_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
