# Generated by Django 5.2 on 2025-05-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0002_rapor_diger_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaporDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secim', models.CharField(choices=[('dogru', 'Bilgi doğru'), ('eksik', 'Eksik bilgi var'), ('yaniltici', 'Yanıltıcı bilgi'), ('alakasi_yok', 'Alakasız rapor')], max_length=20)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='rapor.rapor')),
            ],
        ),
    ]
