# Generated by Django 5.2 on 2025-05-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0003_rapordegerlendirme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uye',
            name='soyisim',
        ),
    ]
