# Generated by Django 5.2 on 2025-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0004_remove_uye_soyisim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapordegerlendirme',
            name='tarih',
        ),
        migrations.AddField(
            model_name='rapor',
            name='adres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapor',
            name='diger_aciklama',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rapor',
            name='olay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rapordegerlendirme',
            name='secim',
            field=models.CharField(choices=[('dogru', 'Bilgi doğru'), ('eksik', 'Eksik bilgi var'), ('yaniltici', 'Yanıltıcı bilgi'), ('alakasi_yok', 'Alakasız rapor')], max_length=50),
        ),
    ]
