# Generated by Django 5.2.1 on 2025-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0005_remove_rapordegerlendirme_tarih_rapor_adres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapor',
            name='diger_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapordegerlendirme',
            name='secim',
            field=models.CharField(choices=[('dogru', 'Bilgi doğru'), ('eksik', 'Eksik bilgi var'), ('yaniltici', 'Yanıltıcı bilgi'), ('alakasi_yok', 'Alakasız rapor')], max_length=20),
        ),
    ]
